Repository webxacademy/lotus_salon, pull requests merged in 2021-12, with the labels that each got.

#20 Team Section
  assets/images/team/Deidre.jpg
  assets/images/team/annie.jpg
  assets/images/team/annika.jpg
  assets/images/team/ashley.jpg
  assets/images/team/callie.jpg
  assets/images/team/dani.jpg
  assets/images/team/gracie.jpg
  assets/images/team/hannah.jpg
  assets/images/team/jordyn.jpg
  assets/images/team/krystal.jpg
  assets/images/team/leanne.jpg
  assets/images/team/maggie.jpg
  assets/images/team/mandy.jpg
  assets/images/team/meghan.jpg
  assets/images/team/savannah.jpg
  index.html
  main.css
Labels: enhancement, good first issue

#21 Added Gallery Section
  index.html
  main.css
Labels: enhancement, good first issue

#26 Fixed Navbar and products close button
  index.html
  main.css
  main.js
Labels: bug

#27 Footer section
  assets/images/apps/Presentation.pdf
  assets/images/apps/android.png
  assets/images/apps/app.png
  assets/images/apps/apple.png
  assets/images/contactUS/1.jpeg
  assets/images/contactUS/2.jpeg
  assets/images/contactUS/3.jpg
  assets/images/contactUS/4.jpeg
  assets/images/gallery/7.jpg
  assets/images/gallery/8.jpg
  assets/images/gallery/9.jpg
  assets/images/review/1.jpeg
  index.html
  main.css
Labels: bug, enhancement, good first issue
